name: Your New Jekyll Site
markdown: redcarpet
pygments: true
baseurl: ""
navbar_items:
  # - title: "to do list"
  #   name: "todo"
  - title: "what i've done"
    name: "portfolio"
  - spacer: "true"
  - title: "all blog posts"
    name: "blog"
  - title: "all reviews"
    name: "reviews"
  - spacer: "true"
  - title: "about me"
    name: "about-me"
  # - title: "utils"
  #   link: "#"
  #   dropdown: 'true'
  #   dropdown_items:
  #     - title: "Core"
  #       link: "/docs/core"
  #     - title: "Time"
  #       link: "/docs/time"
  #     - title: "Utils"
  #       link: "/docs/utils"
